[options]
addons_path = /mnt/extra-addons,/usr/lib/python3/dist-packages/odoo/addons
data_dir = /var/lib/odoo
admin_passwd = $pbkdf2-sha512$600000$LoVw7r137l3rvXcupTSmVA$YMDU.cj6DmvEYq4PUEtFICnk07Hlv92R599HTuPtBZ08VK3SVbG9rntyr5XAux9BAqrm0rsPegrmHX6ddKcgFA
db_host = db
db_port = 5432
db_user = odoo
db_password = odoo
xmlrpc_port = 8069
logfile = /var/log/odoo/odoo.log
log_level = info

